/*====================================================================
                SECTION 3 : PRODUCT ANALYSIS
======================================================================

Objective:
The objective of this section is to analyze product performance
across different categories. This analysis helps identify customer
preferences, high-performing product segments, and sales trends,
enabling better inventory management and business decision-making.

====================================================================*/
/*====================================================================
Query 10 : Analyze Sales by Fat Content

Business Problem:
Blinkit wants to compare the total sales generated by products with
different fat content (Low Fat and Regular) to understand customer
purchasing preferences.

Business Importance:
Analyzing sales by fat content helps identify which product category
customers prefer. These insights support inventory planning,
marketing campaigns, and product stocking decisions.

====================================================================*/

SELECT
    Item_Fat_Content,
    Round(SUM(Item_Outlet_Sales),2) AS Total_Sales
FROM blinkit_data
GROUP BY Item_Fat_Content
ORDER BY Total_Sales DESC ;


-- Observation:
-- The total sales for each fat content category have been calculated
-- and displayed in descending order of sales.


/*====================================================================
Query 11 : Count Products by Fat Content

Business Problem:
Blinkit wants to determine the total number of products available
under each fat content category.

Business Importance:
Understanding the distribution of products by fat content helps
Blinkit evaluate its product portfolio and ensure the right balance
between Low Fat and Regular products based on customer demand.

====================================================================*/

SELECT
    Item_Fat_Content,
    COUNT(*) AS Total_Products
FROM blinkit_data
GROUP BY Item_Fat_Content
ORDER BY Total_Products DESC;

-- Observation:
-- The total number of products in each fat content category is
-- displayed in descending order.



/*====================================================================
Query 12 : Analyze Sales by Item Type

Business Problem:
Blinkit wants to analyze the total sales generated by each product
category to identify the best-performing and lowest-performing
product types.

Business Importance:
Analyzing sales by product category helps Blinkit understand customer
buying preferences, optimize inventory, improve category-wise
marketing strategies, and focus on high-revenue product segments.

====================================================================*/

SELECT
    Item_Type,
    SUM(Item_Outlet_Sales) AS Total_Sales
FROM blinkit_data
GROUP BY Item_Type
ORDER BY Total_Sales DESC;

-- Observation:
-- The analysis shows that Fruits and Vegetables recorded the highest
-- total sales (2,820,059.82), followed by Snack Foods
-- (2,732,786.09) and Household


/*====================================================================
Query 13 : Calculate Average Sales by Item Type

Business Problem:
Blinkit wants to calculate the average sales generated by each
product category to evaluate its overall sales performance.

Business Importance:
Average sales provide a fair comparison between product categories
by showing the typical sales generated per product. This helps
identify categories that consistently perform well, regardless of
the number of products available in each category.

====================================================================*/

SELECT
    Item_Type,
    AVG(Item_Outlet_Sales) AS Average_Sales
FROM blinkit_data
GROUP BY Item_Type
ORDER BY Average_Sales DESC;

-- Observation:
-- Starchy Foods recorded the highest average sales (2,374.33),
-- followed by Seafood (2,326.07), Fruits and Vegetables (2,289.01),
-- Snack Foods (2,277.32), and Household (2,258.78).


/*====================================================================
Query 14 : Top 10 Best-Selling Products

Business Problem:
Blinkit wants to identify the top 10 best-selling products based on
their total sales to understand which products contribute the most
to overall revenue.

Business Importance:
Identifying the best-selling products helps Blinkit prioritize
inventory, improve stock availability, and design targeted marketing
campaigns for high-performing products.

====================================================================*/

SELECT
    Item_Identifier,
    Item_Type,
    SUM(Item_Outlet_Sales) AS Total_Sales
FROM blinkit_data
GROUP BY Item_Identifier, Item_Type
ORDER BY Total_Sales DESC
LIMIT 10;

-- Observation:
-- The top-selling product is FDY55 (Fruits and Vegetables) with
-- total sales of 42,661.80, followed by FDA15 (Dairy) with
-- 41,584.54 and FDZ20 (Fruits and Vegetables) with 40,185.02.
-- The results display the top 10 highest revenue-generating products
-- in descending order of total sales.


/*====================================================================
Query 15 : Identify Bottom 10 Lowest-Selling Products

Business Problem:
Blinkit wants to identify the bottom 10 products with the lowest
sales to evaluate underperforming products and take corrective
business actions.

Business Importance:
Identifying the lowest-selling products helps Blinkit optimize
inventory, improve promotional strategies, review product demand,
and make informed decisions regarding product assortment.

====================================================================*/

SELECT
    Item_Identifier,
    Item_Type,
    SUM(Item_Outlet_Sales) AS Total_Sales
FROM blinkit_data
GROUP BY Item_Identifier, Item_Type
ORDER BY Total_Sales ASC
LIMIT 10;

-- Observation:
-- The lowest-selling product is FDQ60 (Baking Goods) with total
-- sales of 120.50, followed by NCR42 (Household) with 339.90 and
-- FDY43 (Fruits and Vegetables) with 673.79. The results display
-- the bottom 10 products ranked in ascending order of total sales.

/*====================================================================
Query 16 : Analyze Average MRP by Item Type

Business Problem:
Blinkit wants to compare the average Maximum Retail Price (MRP) of
products across different product categories.

Business Importance:
Analyzing the average MRP by product category helps identify premium
and budget-friendly product segments. These insights support pricing
strategies, product positioning, and category-wise business planning.

====================================================================*/

SELECT
    Item_Type,
    AVG(Item_MRP) AS Average_MRP
FROM blinkit_data
GROUP BY Item_Type
ORDER BY Average_MRP DESC;

-- Observation:
-- Household products recorded the highest average MRP (149.42),
-- followed by Dairy (148.50), Starchy Foods (147.84),
-- Snack Foods (146.19), and Fruits and Vegetables (144.58).
-- The results highlight the product categories with the highest
-- average selling prices.

/*====================================================================
Query 17 : Analyze Average Item Visibility by Item Type

Business Problem:
Blinkit wants to analyze the average visibility of products across
different product categories.

Business Importance:
Product visibility plays an important role in attracting customer
attention. This analysis helps evaluate which product categories
receive better shelf visibility and supports merchandising decisions.

====================================================================*/

SELECT
    Item_Type,
    AVG(Item_Visibility) AS Average_Item_Visibility
FROM blinkit_data
GROUP BY Item_Type
ORDER BY Average_Item_Visibility DESC;

-- Observation:
-- Breakfast products recorded the highest average item visibility
-- (0.0857), followed by Seafood (0.0750), Dairy (0.0724),
-- Baking Goods (0.0692), and Fruits and Vegetables (0.0685).
-- The results identify the product categories with the highest
-- average shelf visibility.

/*====================================================================
Query 18 : Count Products by Item Type

Business Problem:
Blinkit wants to determine the number of products available in each
product category.

Business Importance:
Understanding the distribution of products across categories helps
evaluate product assortment, inventory planning, and category
management strategies.

====================================================================*/

SELECT
    Item_Type,
    COUNT(*) AS Total_Products
FROM blinkit_data
GROUP BY Item_Type
ORDER BY Total_Products DESC;

-- Observation:
-- Fruits and Vegetables contains the highest number of products
-- (1,232), followed by Snack Foods (1,200), Household (910),
-- Frozen Foods (856), and Dairy (682). The results show the
-- distribution of products across different categories in
-- descending order.

