/*====================================================================
                SECTION 4 : OUTLET ANALYSIS
======================================================================

Objective:
The objective of this section is to analyze the performance of
different outlets based on their size, location, type, and
establishment year. This analysis helps identify high-performing
outlets and supports strategic business decisions related to
expansion, inventory management, and sales optimization.

====================================================================*/

/*====================================================================
Query 19 : Analyze Sales by Outlet Size

Business Problem:
Blinkit wants to compare the total sales generated by outlets of
different sizes (Small, Medium, and High).

Business Importance:
Analyzing sales by outlet size helps Blinkit understand which outlet
size contributes the most revenue. These insights support expansion
planning, inventory allocation, and operational decision-making.

====================================================================*/

SELECT
    Outlet_Size,
    round(sum(Item_Outlet_Sales),2) AS Total_Sales
FROM blinkit_data
GROUP BY Outlet_Size
ORDER BY Total_Sales DESC;

-- Observation:
-- Medium-sized outlets generated the highest total sales
-- (11,882,249.63), followed by Small outlets (4,566,212.20)
-- and High outlets (2,142,663.58). The results indicate that
-- Medium-sized outlets are the largest contributors to overall
-- sales.


/*====================================================================
Query 20 : Analyze Sales by Outlet Location Type

Business Problem:
Blinkit wants to compare the total sales generated across different
outlet location tiers (Tier 1, Tier 2, and Tier 3) to identify
which market contributes the most revenue.

Business Importance:
Analyzing sales by outlet location helps Blinkit understand regional
performance, identify high-revenue markets, and make informed
decisions regarding expansion, inventory allocation, and marketing
strategies.

====================================================================*/

SELECT
    Outlet_Location_Type,
    ROUND(SUM(Item_Outlet_Sales), 2) AS Total_Sales
FROM blinkit_data
GROUP BY Outlet_Location_Type
ORDER BY Total_Sales DESC;

-- Observation:
-- Tier 3 outlets generated the highest total sales
-- (7,636,752.63), followed by Tier 2 outlets
-- (6,472,313.71) and Tier 1 outlets (4,482,059.07).
-- The results indicate that Tier 3 outlets contribute the
-- highest share of overall sales.


/*====================================================================
Query 21 : Analyze Sales by Outlet Type

Business Problem:
Blinkit wants to compare the total sales generated by different
outlet types to identify the highest-performing business format.

Business Importance:
Analyzing sales by outlet type helps Blinkit evaluate the
performance of each outlet format. These insights support
business expansion, operational planning, and investment
decisions.

====================================================================*/

SELECT
    Outlet_Type,
    ROUND(SUM(Item_Outlet_Sales), 2) AS Total_Sales
FROM blinkit_data
GROUP BY Outlet_Type
ORDER BY Total_Sales DESC;

-- Observation:
-- Supermarket Type1 generated the highest total sales
-- (12,917,342.26), followed by Supermarket Type3
-- (3,453,926.05), Supermarket Type2 (1,851,822.83),
-- and Grocery Store (368,034.27). The results indicate
-- that Supermarket Type1 is the highest revenue-generating
-- outlet type.


/*====================================================================
Query 22 : Count Products by Outlet Type

Business Problem:
Blinkit wants to determine the number of products available across
different outlet types.

Business Importance:
Understanding the product distribution across outlet types helps
Blinkit evaluate inventory allocation, outlet capacity, and product
availability. These insights support inventory planning and resource
optimization.

====================================================================*/

SELECT
    Outlet_Type,
    COUNT(*) AS Total_Products
FROM blinkit_data
GROUP BY Outlet_Type
ORDER BY Total_Products DESC;

-- Observation:
-- Supermarket Type1 contains the highest number of products
-- (5,577), followed by Grocery Store (1,083), Supermarket Type3
-- (935), and Supermarket Type2 (928). The results show the
-- distribution of products across different outlet types in
-- descending order.


/*====================================================================
Query 23 : Analyze Sales by Outlet Establishment Year

Business Problem:
Blinkit wants to analyze the total sales generated by outlets based
on their establishment year to understand how outlet age impacts
business performance.

Business Importance:
Analyzing sales by outlet establishment year helps Blinkit evaluate
the performance of outlets opened in different years. These insights
support expansion planning, outlet performance evaluation, and
long-term business growth strategies.

====================================================================*/

SELECT
    Outlet_Establishment_Year,
    ROUND(SUM(Item_Outlet_Sales), 2) AS Total_Sales
FROM blinkit_data
GROUP BY Outlet_Establishment_Year
ORDER BY Outlet_Establishment_Year;

-- Observation:
-- Outlets established in 1985 generated the highest total sales
-- (3,633,620.14), followed by outlets established in 1999
-- (2,183,969.81), 1987 (2,142,663.58), and 1997
-- (2,118,395.17). The results show the sales performance of
-- outlets based on their establishment year.


/*====================================================================
Query 24 : Calculate Average Sales by Outlet Size

Business Problem:
Blinkit wants to compare the average sales generated by outlets of
different sizes.

Business Importance:
Comparing the average sales across outlet sizes helps evaluate which
outlet size performs more efficiently on average. These insights
support outlet expansion, inventory planning, and operational
decision-making.

====================================================================*/

SELECT
    Outlet_Size,
    ROUND(AVG(Item_Outlet_Sales), 2) AS Average_Sales
FROM blinkit_data
GROUP BY Outlet_Size
ORDER BY Average_Sales DESC;

-- Observation:
-- High-sized outlets recorded the highest average sales (2,299.00),
-- followed by Medium-sized outlets (2,283.73) and Small-sized
-- outlets (1,912.15). The results indicate that High-sized outlets
-- achieve the highest average sales per product.

/*====================================================================
Query 25 : Analyze Average Sales by Outlet Location Type

Business Problem:
Blinkit wants to compare the average sales generated across
different outlet location tiers (Tier 1, Tier 2, and Tier 3).

Business Importance:
Analyzing average sales by outlet location helps evaluate the
sales efficiency of each location tier. This insight supports
location-based expansion strategies, resource allocation, and
market performance evaluation.

====================================================================*/

SELECT
    Outlet_Location_Type,
    ROUND(AVG(Item_Outlet_Sales), 2) AS Average_Sales
FROM blinkit_data
GROUP BY Outlet_Location_Type
ORDER BY Average_Sales DESC;

-- Observation:
-- Tier 2 outlets recorded the highest average sales (2,323.99),
-- followed by Tier 3 outlets (2,279.63) and Tier 1 outlets
-- (1,876.91). The results indicate that Tier 2 outlets achieve
-- the highest average sales per product among all location tiers.